#!/bin/bash

function stop_service() {
  local NAME=$1
  invoke-rc.d ${NAME} stop
}

# shutdown existing services
if [[ -f "/etc/init.d/mycroft-speech-client" ]]; then
  stop_service "mycroft-speech-client"
fi

if [[ -f "/etc/init.d/mycroft-skills" ]]; then
  stop_service "mycroft-skills"
fi

if [[ -f "/etc/init.d/mycroft-messagebus" ]]; then
  stop_service "mycroft-messagebus"
fi

if [[ -f "/etc/init.d/mycroft-enclosure-client" ]]; then
 /etc/init.d/mycroft-enclosure-client stop
fi

id -u mycroft &>/dev/null || useradd mycroft

adduser mycroft input
adduser mycroft audio
adduser mycroft dialout

if [ ! -d /home/mycroft ]; then
    mkdir -p /home/mycroft
    chown -R mycroft:mycroft /home/mycroft
fi
